/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.wts.kotlin

//import kotlinx.coroutines.experimental.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    val sqn = sequence<Int> {
        yield(1)
    }

    println(Thread.currentThread())
//    launch{
//
//    }
}

fun process(n: Int): Int {
    println("process: ${Thread.currentThread()}")
    return n;
}

